settings:
  index:
    # single node, no sharding
    number_of_shards: 1
    number_of_replicas: 0
    refresh_interval: 60s
mappings:
  dynamic: false # disable dynamic mapping
  properties:
    scientific_name:
      type: text
    common_name:
      type: text
      analyzer: english
    family_common_name:
      type: text
    synonyms:
      type: text
    common_names:
      type: text
